name = "cloudflare-tech-talk"
main = "src/index.ts"
compatibility_date = "2025-01-11"
compatibility_flags = ["nodejs_compat"]
account_id = "6328a3531a28b413e6ca1e95f794a4dc"

# Static assets
assets = { directory = "public" }


# Custom domain route
routes = [{ pattern = "refactory.com.au", custom_domain = true }]

[observability]
enabled = true

# Durable Objects
[[durable_objects.bindings]]
name = "SLIDE_ROOM"
class_name = "SlideRoom"

[[durable_objects.bindings]]
name = "POLL_ROOM"
class_name = "PollRoom"

[[durable_objects.bindings]]
name = "CONTAINER_STATUS"
class_name = "ContainerStatus"

# Durable Object migrations
[[migrations]]
tag = "v3"
new_sqlite_classes = ["SlideRoom"]
new_classes = ["PollRoom", "ContainerStatus"]

# Queue Producer
[[queues.producers]]
binding = "VOTE_QUEUE"
queue = "vote-queue"

# Queue Consumer
[[queues.consumers]]
queue = "vote-queue"
max_batch_size = 100
max_batch_timeout = 5

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "tech-talk-db"
database_id = "a9f392a1-a370-4be3-922f-51070793c868"
